import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {GIFT_REGISTRY,REGULAR_LETTER_IDS} from '../lib/gifts.ts';
const {PGlite}=await import(process.env.PHOTO_PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create table auth.identities(user_id uuid,provider text);
create function auth.uid() returns uuid language sql as 'select null::uuid';
create table public.profiles("userId" uuid primary key,nickname text,gender text,"birthYear" int);`);
const migration=async name=>db.exec(await fs.readFile(new URL(`../supabase/migrations/${name}.sql`,import.meta.url),'utf8'));
for(const name of ['20260915_progression','20260915_gifts','20260915_photo_collection','20260917_reward_rules','20260921_letter_story','20260922_photo_album','20260923_photo_props','20260924_photo_first_click','20260925_admin_tools'])await migration(name);
const user='00000000-0000-4000-8000-000000000c01';
await db.query('insert into auth.users(id) values ($1)',[user]);
const state=async()=>(await db.query('select * from public.user_progression where user_id=$1',[user])).rows[0];
const mutate=async(action,amount=0,reason='',event='',category='general')=>(await db.query('select public.mutate_progression($1,$2,$3,$4,$5,p_category=>$6) r',[user,action,amount,reason,event,category])).rows[0].r;
await mutate('ensure');
assert.equal((await mutate('add',30,'daily_login')).delta,30);
assert.equal((await mutate('add',5,'interaction','original','pet')).delta,5);
const old=await state();
await migration('20260926_progression_latency');
assert.deepEqual((await state()).reward_receipts,{});
assert.equal((await state()).heart_coin_balance,old.heart_coin_balance);
assert.equal((await db.query('select count(*)::int n from public.progression_receipts')).rows[0].n,Object.keys(old.reward_receipts).length);
assert.equal((await mutate('add',30,'daily_login')).delta,0,'old login retained');
assert.equal((await mutate('add',5,'interaction','original','pet')).delta,0,'old receipt retained');
await assert.rejects(mutate('add',5,'interaction','original','bath'),/different payload/);
assert.equal((await mutate('add',5,'interaction','new','bath')).delta,5);
assert.equal((await mutate('add',5,'interaction','new','bath')).delta,0);
// Replay across a date reset still must not issue another reward.
await db.query('update public.user_progression set progression_date=progression_date-1 where user_id=$1',[user]);
assert.equal((await mutate('add',5,'interaction','new','bath')).delta,0);
// Existing atomic gift purchase now includes the transaction's balance/ownership snapshot.
await db.query('update public.user_progression set heart_coin_balance=1000 where user_id=$1',[user]);
const purchase=async()=>(await db.query("select public.gift_gameplay($1,'purchase','mimi_plush',null,null,'cabinet_order',$2,$3) r",[user,JSON.stringify(GIFT_REGISTRY),REGULAR_LETTER_IDS])).rows[0].r;
const bought=await purchase();assert.equal(bought.ok,true);assert.equal(bought.progression.heart_coin_balance,900);assert(bought.progression.owned_gift_ids.includes('mimi_plush'));
assert.equal((await purchase()).reason,'already_owned');assert.equal((await state()).heart_coin_balance,900);
// Letter receipt payload survives normalization, including the reread result.
const letter=(await state()).letter_state;
const commit=async()=>(await db.query('select public.commit_letter_event($1,$2,$3,$4,$5,$6) r',[user,letter.version,JSON.stringify(letter),['letter_01'],'letter-retry','letter_01'])).rows[0].r;
assert.equal((await commit()).delta,20);const replay=await commit();assert.equal(replay.delta,0);assert.equal(replay.letterId,'letter_01');assert.equal(replay.duplicate,true);
const catalog=JSON.parse(await fs.readFile(new URL('../lib/photo-catalog.json',import.meta.url),'utf8'));
const photoEvent=crypto.randomUUID();
const photo=async()=>(await db.query("select public.acquire_photo_album($1,'wardrobe',$2,$3,$4) r",[user,photoEvent,JSON.stringify(catalog),JSON.stringify({outfit:0})])).rows[0].r;
assert.equal((await photo()).delta,30);assert.equal((await photo()).photoId,null);
assert.deepEqual(Object.keys((await state()).reward_receipts),['photo_last_event_at']);
const before=await state();await migration('20260926_progression_latency');assert.deepEqual(await state(),before,'migration rerun is safe');
await db.exec('set role authenticated');
await assert.rejects(db.query('select * from public.progression_receipts'),/permission denied/);
await assert.rejects(db.query('select public.progression_receipt($1,$2)',[user,'original']),/permission denied/);
await db.exec('reset role');
await db.query('delete from auth.users where id=$1',[user]);assert.equal((await db.query('select count(*)::int n from public.progression_receipts')).rows[0].n,0);
await db.close();
console.log('PASS: lossless receipt migration/replay, reward caps, gift transaction snapshot, letter/photo dedupe, migration rerun, RLS, account cleanup');
